force_cast: warning

identifier_name:
    min_length: 1

type_name:
    allowed_symbols: [_]
    min_length: 1

line_length:
    warning: 120
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true

nesting:
    type_level: 3
