lane :tests do
    ios_tests
    mac_tests
end

lane :ios_tests do
    run_tests(workspace: "ABit.xcworkspace",
              scheme: "ABit",
              devices: ["iPhone 12 mini"],
              catalyst_platform: "ios")
end

lane :mac_tests do
    match(type: "development", readonly: is_ci)
    run_tests(workspace: "ABit.xcworkspace",
              scheme: "ABit",
              catalyst_platform: "macos")
end

after_all do |lane|
    print("Successfully ran (#{lane})!")
end

error do |lane, exception|
    print("Failed to complete (#{lane}) with exception (#{exception})!")
end
