devices([
  "iPhone 12 Pro Max",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch) (4th generation)",
  "iPad Pro (9.7-inch)",
])

languages(["en-UK"])

# The name of the scheme which contains the UI Tests
scheme("ABitScreenshots")

# Where should the resulting screenshots be stored?
output_directory("./Automation/Screenshots")

# Set the status bar to 9:41 AM, and show full battery and reception.
override_status_bar(true)

# Clean project before building
clean(true)

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)


# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
