name: Screenshots 
on: [push]
jobs:
  tests:
    name: Screenshots 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true  
            
    - name: Run Screenshot Capture 
      run: |
        brew install fastlane
        bundle exec fastlane app_store_screenshots
