name: AutomatedTests
on: [push]
jobs:
  tests:
    name: UnitTests
    runs-on: macos-latest

    steps:
    - name: Checkout ABit
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Checkout Fastlane Match Repo
      uses: actions/checkout@v2
      with:
        repository: NSGoat/Fastlane-Match
        ref: main
        token: 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
        clean: false

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    - name: Run Tests
      run: |
        brew install fastlane
        bundle exec fastlane tests
