name: AutomatedTests
on:
  pull_request:
    branches:
      - main
      - release/**
      - develop


jobs:
  tests:
    name: UnitTests
    runs-on: macos-latest

    steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    - name: Install Fastlane
      run: brew install fastlane

    - name: Checkout Fastlane Match Repo
      uses: actions/checkout@v2
      with:
        repository: NSGoat/Fastlane-Match
        ref: main
        token: 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

    - name: Install certificates with Match
      run: bundle exec fastlane match development

    - name: Checkout ABit
      uses: actions/checkout@v2

    - name: Run Tests
      run: bundle exec fastlane tests
